# Generated by Django 5.1 on 2024-08-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subcategory',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
