# Generated by Django 5.1 on 2024-08-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_question_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryquestion',
            options={'verbose_name': 'Categoria de Pergunta', 'verbose_name_plural': 'Categorias de Perguntas'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subcategoria', 'verbose_name_plural': 'Subcategorias'},
        ),
        migrations.AddField(
            model_name='answer',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
