# Generated by Django 5.1 on 2024-09-05 17:19

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_question_recommendation_alter_answer_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='attachment_evaluator',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.models.rename_attachment_evaluator),
        ),
        migrations.AlterField(
            model_name='answer',
            name='attachment_respondent',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.models.rename_attachment_respondent),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('evaluation', 'question'), name='unique_answer_per_question_in_evaluation'),
        ),
    ]
