# Generated by Django 5.1 on 2024-09-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_answer_attachment_evaluator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_respondent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
