# Generated by Django 5.1 on 2024-10-17 10:57

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_actionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.models.rename_attachment_action_plan),
        ),
    ]
