# Generated by Django 5.0.13 on 2025-07-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_actionplan_response_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dominio',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
