# Generated by Django 5.0.13 on 2025-09-17 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_company_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=18),
        ),
        migrations.CreateModel(
            name='Polo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome do Polo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companies', models.ManyToManyField(blank=True, related_name='poles', to='core.company')),
                ('superusers', models.ManyToManyField(blank=True, limit_choices_to={'is_superuser': True}, related_name='managed_poles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Polo',
                'verbose_name_plural': 'Polos',
                'ordering': ('name',),
            },
        ),
    ]
