# Generated by Django 5.0.13 on 2025-09-18 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_company_cnpj_polo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polo',
            name='superusers',
        ),
        migrations.AddField(
            model_name='polo',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='poles', to=settings.AUTH_USER_MODEL),
        ),
    ]
