# Generated by Django 5.0.13 on 2025-09-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_company_user_company_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='users',
        ),
    ]
