# Generated by Django 5.0.13 on 2025-11-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_user_company_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='response_choice',
            field=models.CharField(blank=True, choices=[('NA', 'Não Aplicável'), ('C', 'Conforme'), ('NC', 'Não Conforme'), ('A', 'Em Análise')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='response_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
