# Generated by Django 5.0.13 on 2026-03-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_evaluation_status_storedfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='storage_provider',
            field=models.CharField(choices=[('onedrive', 'OneDrive'), ('local', 'Local')], default='onedrive', max_length=20),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='provider',
            field=models.CharField(choices=[('onedrive', 'OneDrive'), ('local', 'Local')], default='onedrive', max_length=40),
        ),
    ]
