# Generated by Django 5.0.13 on 2025-04-11 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_actionplan_response_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('empregados', models.IntegerField(blank=True, null=True)),
                ('horas_homem_exposicao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acidentes_com_afastamento', models.IntegerField(blank=True, null=True)),
                ('acidentes_sem_afastamento', models.IntegerField(blank=True, null=True)),
                ('acidentes_com_afastamento_tipicos', models.IntegerField(blank=True, null=True)),
                ('acidentes_transito', models.IntegerField(blank=True, null=True)),
                ('taxa_com_afastamento', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('taxa_sem_afastamento', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('acidentados_registraveis', models.IntegerField(blank=True, null=True)),
                ('gravidade', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('dias_perdidos_debitados', models.IntegerField(blank=True, null=True)),
                ('fatalidades', models.IntegerField(blank=True, null=True)),
                ('incidencia', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('lma_nca', models.IntegerField(blank=True, null=True)),
                ('lma_tfca', models.IntegerField(blank=True, null=True)),
                ('outros', models.IntegerField(blank=True, null=True)),
                ('primeiros_socorros', models.IntegerField(blank=True, null=True)),
                ('total_acidentes_registraveis', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('trabalho_restrito', models.IntegerField(blank=True, null=True)),
                ('tratamento_medico', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rems', to='core.company')),
            ],
            options={
                'verbose_name': 'REM',
                'verbose_name_plural': 'REMs',
            },
        ),
        migrations.AddConstraint(
            model_name='rem',
            constraint=models.UniqueConstraint(fields=('company', 'periodo'), name='unique_rem_per_company_periodo'),
        ),
    ]
