# Generated by Django 5.0.13 on 2025-04-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rem',
            old_name='total_acidentes_registraveis',
            new_name='total_incidentes_registraveis',
        ),
    ]
