# Generated by Django 5.0.13 on 2025-04-23 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_actionplan_response_company'),
        ('rem', '0002_rename_total_acidentes_registraveis_rem_total_incidentes_registraveis'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieselConsumido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('diesel_consumido', models.IntegerField(blank=True, default=0, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diesel_consumidos', to='core.company')),
            ],
            options={
                'verbose_name': 'Diesel Consumido',
                'verbose_name_plural': 'Diesel Consumidos',
            },
        ),
        migrations.CreateModel(
            name='FuncionariosDemitidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('funcionarios_demitidos', models.IntegerField(blank=True, default=0, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios_demitidos', to='core.company')),
            ],
            options={
                'verbose_name': 'Funcionarios Demitidos',
                'verbose_name_plural': 'Funcionarios Demitidos',
            },
        ),
        migrations.AddConstraint(
            model_name='dieselconsumido',
            constraint=models.UniqueConstraint(fields=('company', 'periodo'), name='unique_diesel_consumido_per_company_periodo'),
        ),
        migrations.AddConstraint(
            model_name='funcionariosdemitidos',
            constraint=models.UniqueConstraint(fields=('company', 'periodo'), name='unique_funcionarios_demitidos_per_company_periodo'),
        ),
    ]
