# Generated by Django 5.0.13 on 2025-06-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0003_dieselconsumido_funcionariosdemitidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rem',
            name='teste',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
