# Generated by Django 5.0.13 on 2025-06-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0004_rem_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rem',
            name='teste',
        ),
    ]
